<?php

namespace ApiBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequestRepository extends EntityRepository
{
    /**
     * Get requests by filters
     *
     * @param array $filters
     * @return array
     */
    public function findRequest($filters)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        $qb->select('r')
            ->from('ApiBundle:Request', 'r')
            ->where($qb->expr()->andX(
                (!empty($filters['id']) ? $qb->expr()->eq('r.id', ':id') : null),
                (!empty($filters['route']) ? $qb->expr()->eq('r.route', ':route') : null),
                (!empty($filters['ip']) ? $qb->expr()->eq('r.ip', ':ip') : null),
                (!empty($filters['method']) ? $qb->expr()->like('r.method', ':method') : null),
                (!empty($filters['last_days']) ? $qb->expr()->gt('r.created', ':created') : null),
                (!empty($filters['search'])
                    ? $qb->expr()->orX(
                        $qb->expr()->like('r.headers', ':search'),
                        $qb->expr()->like('r.body', ':search')
                    )
                    : null
                )
            ));

        if (!empty($filters['id'])) {
            $qb->setParameter('id', (int)$filters['id']);
        }
        if (!empty($filters['route'])) {
            $qb->setParameter('route', $filters['route']);
        }
        if (!empty($filters['ip'])) {
            $qb->setParameter('ip', $filters['ip']);
        }
        if (!empty($filters['method'])) {
            $qb->setParameter('method', $filters['method']);
        }
        if (!empty($filters['last_days']) && (int)$filters['last_days']) {
            $date = new \DateTime("now");
            $date->sub(new \DateInterval("P{$filters['last_days']}D"));
            $qb->setParameter('created', $date->format('Y-m-d H:i:s'));
        }
        if (!empty($filters['search'])) {
            $qb->setParameter('search', '%' . $filters['search'] . '%');
        }

        return $qb->getQuery()->getResult();
    }
}
